{% set name = "ui5-cli" %}
{% set version = "3.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SAP/ui5-cli/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c97c5521587de2d447d873cb24bf42bc1d59bad7485d2142e885783ad595ac77

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - ui5 --help

about:
  home: https://github.com/SAP/ui5-cli
  license: Apache-2.0
  license_file:
    - LICENSES/Apache-2.0.txt
    - ThirdPartyLicenses.txt
  summary: 'UI5 Tooling: CLI'

extra:
  recipe-maintainers:
    - xhochy
