{% set name = "ui5-cli" %}
{% set version = "2.14.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SAP/ui5-cli/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fdd4b40613bf07d114e89ac145ebb67880ce8480a37e309a54003ce98f13fc02

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - ui5 --help

about:
  home: https://github.com/SAP/ui5-cli
  license: Apache-2.0
  license_file:
    - LICENSES/Apache-2.0.txt
    - ThirdPartyLicenses.txt
  summary: 'UI5 Tooling: CLI'

extra:
  recipe-maintainers:
    - xhochy
