{% set name = "ui5-cli" %}
{% set version = "2.14.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SAP/ui5-cli/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8db25cdd47f015ea90a98730e7c5e909c10e313ea8b5fdcaffed114f7251851d

build:
  number: 2

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - ui5 --help

about:
  home: https://github.com/SAP/ui5-cli
  license: Apache-2.0
  license_file:
    - LICENSES/Apache-2.0.txt
    - ThirdPartyLicenses.txt
  summary: 'UI5 Tooling: CLI'

extra:
  recipe-maintainers:
    - xhochy
