{% set name = "ui5-cli" %}
{% set version = "4.0.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/@ui5/cli/-/cli-{{ version }}.tgz
  sha256: 082c1951010971cf6be825ce2a4af2af98851ab0ce4646a78c07cb7f715aab2b

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - ui5 --help

about:
  home: https://github.com/SAP/ui5-cli
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  summary: 'UI5 Tooling: CLI'

extra:
  recipe-maintainers:
    - danielnachun
    - xhochy
