{% set name = "ui5-cli" %}
{% set version = "4.0.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/@ui5/cli/-/cli-{{ version }}.tgz
  sha256: 0e0903894354355ae98430bf39079d69068ddb6b6ba4363031e0f99a7ef18bed

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - ui5 --help

about:
  home: https://github.com/SAP/ui5-cli
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  summary: 'UI5 Tooling: CLI'

extra:
  recipe-maintainers:
    - danielnachun
    - xhochy
