{% set name = "ui5-cli" %}
{% set version = "4.0.35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/@ui5/cli/-/cli-{{ version }}.tgz
  sha256: 4a61246dd1a1c9ba20489f5c880380550e99627d24615324c65ed54ee434a2ac

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - ui5 --help

about:
  home: https://github.com/SAP/ui5-cli
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  summary: 'UI5 Tooling: CLI'

extra:
  recipe-maintainers:
    - danielnachun
    - xhochy
