{% set name = "ui5-cli" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SAP/ui5-cli/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1c03b8857cdb30ab2324d0ad47748293026b1622ddb66facdee0e8011054e743

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - ui5 --help

about:
  home: https://github.com/SAP/ui5-cli
  license: Apache-2.0
  license_file:
    - LICENSES/Apache-2.0.txt
    - ThirdPartyLicenses.txt
  summary: 'UI5 Tooling: CLI'

extra:
  recipe-maintainers:
    - xhochy
