schema_version: 1

context:
  version: "4.0.43"

package:
  name: ui5-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@ui5/cli/-/cli-${{ version }}.tgz
  sha256: 8d0b958d257171b6d9684d65546e5cf93738204abe39a257d21963f291b64e8f

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - ui5 --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  summary: "UI5 Tooling: CLI"
  homepage: https://github.com/SAP/ui5-cli

extra:
  recipe-maintainers:
    - danielnachun
    - xhochy
