schema_version: 1

context:
  version: "4.0.41"

package:
  name: ui5-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@ui5/cli/-/cli-${{ version }}.tgz
  sha256: 22be50f39b4df22cd336308fbb8f5106bfd116439c058df506ca3a4908a99151

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - ui5 --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  summary: "UI5 Tooling: CLI"
  homepage: https://github.com/SAP/ui5-cli

extra:
  recipe-maintainers:
    - danielnachun
    - xhochy
